version: '3.8'

services:
  frontend:
    build:
      context: .
      target: frontend
    ports:
      - 5173:80
  backend:
    build:
      context: .
      target: backend
    ports:
      - 8080:8080
